// Knockout JavaScript library v2.1.0
// (c) Steven Sanderson - http://knockoutjs.com/
// License: MIT (http://www.opensource.org/licenses/mit-license.php)

(function() {function i(w){throw w;}var l=!0,n=null,o=!1;function q(w){return function(){return w}};var v=window,x=document,B=navigator,E=window.jQuery,F=void 0;
function Z(w){function $(a,d,c,e,f){var g=[],a=b.h(function(){var a=d(c,f)||[];0<g.length&&(L(g),b.a.Na(g,a),e&&e(c,a));g.splice(0,g.length);b.a.O(g,a)},n,{disposeWhenNodeIsRemoved:a,disposeWhen:function(){return 0==g.length||!b.a.X(g[0])}});return{xb:g,h:a}}function L(a){for(;a.length&&!b.a.X(a[0]);)a.splice(0,1);if(1<a.length){for(var d=a[0],c=a[a.length-1],e=[d];d!==c;){d=d.nextSibling;if(!d)return;e.push(d)}Array.prototype.splice.apply(a,[0,a.length].concat(e))}}function M(a,d,c,e,f){var f=f||
{},g=a&&G(a),g=g&&g.ownerDocument,h=f.templateEngine||H;b.ua.mb(c,h,g);c=h.renderTemplate(c,e,f,g);("number"!=typeof c.length||0<c.length&&"number"!=typeof c[0].nodeType)&&i(Error("Template engine must return an array of DOM nodes"));g=o;switch(d){case "replaceChildren":b.e.T(a,c);g=l;break;case "replaceNode":b.a.Na(a,c);g=l;break;case "ignoreTargetNode":break;default:i(Error("Unknown renderMode: "+d))}g&&(N(c,e),f.afterRender&&f.afterRender(c,e.$data));return c}function G(a){return a.nodeType?a:
0<a.length?a[0]:n}function N(a,d){if(a.length){var c=a[0],e=a[a.length-1];O(c,e,function(a){b.ya(d,a)});O(c,e,function(a){b.t.Wa(a,[d])})}}function O(a,d,c){for(var e,d=b.e.nextSibling(d);a&&(e=a)!==d;)a=b.e.nextSibling(e),(1===e.nodeType||8===e.nodeType)&&c(e)}function P(a,d,c){for(var a=b.g.Z(a),e=b.g.F,f=0;f<a.length;f++){var g=a[f].key;if(e.hasOwnProperty(g)){var h=e[g];"function"===typeof h?(g=h(a[f].value))&&i(Error(g)):h||i(Error("This template engine does not support the '"+g+"' binding within its templates"))}}a=
"ko.__tr_ambtns(function(){return(function(){return{"+b.g.$(a)+"} })()})";return c.createJavaScriptEvaluatorBlock(a)+d}function Q(a,d,c,e){function f(a){return function(){return j[a]}}function g(){return j}var h=0,j,k;b.h(function(){var m=c&&c instanceof b.A?c:new b.A(b.a.d(c)),p=m.$data;e&&b.Sa(a,m);if(j=("function"==typeof d?d():d)||b.K.instance.getBindings(a,m)){if(0===h){h=1;for(var s in j){var t=b.c[s];t&&8===a.nodeType&&!b.e.z[s]&&i(Error("The binding '"+s+"' cannot be used with virtual elements"));
if(t&&"function"==typeof t.init&&(t=(0,t.init)(a,f(s),g,p,m))&&t.controlsDescendantBindings)k!==F&&i(Error("Multiple bindings ("+k+" and "+s+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")),k=s}h=2}if(2===h)for(s in j)(t=b.c[s])&&"function"==typeof t.update&&(0,t.update)(a,f(s),g,p,m)}},n,{disposeWhenNodeIsRemoved:a});return{Gb:k===F}}function R(a,d,c){var e=l,f=1===d.nodeType;f&&b.e.Ia(d);if(f&&c||b.K.instance.nodeHasBindings(d))e=
Q(d,n,a,c).Gb;e&&S(a,d,!f)}function S(a,d,c){for(var e=b.e.firstChild(d);d=e;)e=b.e.nextSibling(d),R(a,d,c)}function T(a,b){var c=U(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:n}function U(a,b){for(var c=a,e=1,f=[];c=c.nextSibling;){if(C(c)&&(e--,0===e))return f;f.push(c);u(c)&&e++}b||i(Error("Cannot find closing comment tag to match: "+a.nodeValue));return n}function C(a){return 8==a.nodeType&&(D?a.text:a.nodeValue).match(aa)}function u(a){return 8==a.nodeType&&(D?a.text:a.nodeValue).match(ba)}
function I(a,b){for(var c=n;a!=c;)c=a,a=a.replace(ca,function(a,c){return b[c]});return a}function da(){var a=[],d=[];this.save=function(c,e){var f=b.a.j(a,c);0<=f?d[f]=e:(a.push(c),d.push(e))};this.get=function(c){c=b.a.j(a,c);return 0<=c?d[c]:F}}function V(a,b,c){function e(e){var g=b(a[e]);switch(typeof g){case "boolean":case "number":case "string":case "function":f[e]=g;break;case "object":case "undefined":var h=c.get(g);f[e]=h!==F?h:V(g,b,c)}}c=c||new da;a=b(a);if(!("object"==typeof a&&a!==n&&
a!==F&&!(a instanceof Date)))return a;var f=a instanceof Array?[]:{};c.save(a,f);var g=a;if(g instanceof Array){for(var h=0;h<g.length;h++)e(h);"function"==typeof g.toJSON&&e("toJSON")}else for(h in g)e(h);return f}function W(a,d){if(a)if(8==a.nodeType){var c=b.t.Ja(a.nodeValue);c!=n&&d.push({jb:a,yb:c})}else if(1==a.nodeType)for(var c=0,e=a.childNodes,f=e.length;c<f;c++)W(e[c],d)}function X(a,d,c){c&&d!==b.k.r(a)&&b.k.V(a,d);d!==b.k.r(a)&&b.a.wa(a,"change")}var b="undefined"!==typeof w?w:{};b.b=
function(a,d){for(var c=a.split("."),e=b,f=0;f<c.length-1;f++)e=e[c[f]];e[c[c.length-1]]=d};b.s=function(a,b,c){a[b]=c};b.version="2.1.0";b.b("version",b.version);b.a=new function(){function a(a,d){if("input"!==b.a.u(a)||!a.type||"click"!=d.toLowerCase())return o;var c=a.type;return"checkbox"==c||"radio"==c}var d=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,c={},e={};c[/Firefox\/2/i.test(B.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];c.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");
for(var f in c){var g=c[f];if(g.length)for(var h=0,j=g.length;h<j;h++)e[g[h]]=f}var k={propertychange:l},m,c=3;f=x.createElement("div");for(g=f.getElementsByTagName("i");f.innerHTML="<\!--[if gt IE "+ ++c+"]><i></i><![endif]--\>",g[0];);m=4<c?c:F;return{Da:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],n:function(a,b){for(var d=0,c=a.length;d<c;d++)b(a[d])},j:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var d=0,c=a.length;d<
c;d++)if(a[d]===b)return d;return-1},ab:function(a,b,d){for(var c=0,e=a.length;c<e;c++)if(b.call(d,a[c]))return a[c];return n},ea:function(a,d){var c=b.a.j(a,d);0<=c&&a.splice(c,1)},Aa:function(a){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)0>b.a.j(d,a[c])&&d.push(a[c]);return d},W:function(a,b){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)d.push(b(a[c]));return d},da:function(a,b){for(var a=a||[],d=[],c=0,e=a.length;c<e;c++)b(a[c])&&d.push(a[c]);return d},O:function(a,b){if(b instanceof Array)a.push.apply(a,
b);else for(var d=0,c=b.length;d<c;d++)a.push(b[d]);return a},extend:function(a,b){if(b)for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a},ia:function(a){for(;a.firstChild;)b.removeNode(a.firstChild)},Ab:function(a){for(var a=b.a.M(a),d=x.createElement("div"),c=0,e=a.length;c<e;c++)b.G(a[c]),d.appendChild(a[c]);return d},T:function(a,d){b.a.ia(a);if(d)for(var c=0,e=d.length;c<e;c++)a.appendChild(d[c])},Na:function(a,d){var c=a.nodeType?[a]:a;if(0<c.length){for(var e=c[0],f=e.parentNode,g=0,
h=d.length;g<h;g++)f.insertBefore(d[g],e);g=0;for(h=c.length;g<h;g++)b.removeNode(c[g])}},Qa:function(a,b){7>m?a.setAttribute("selected",b):a.selected=b},D:function(a){return(a||"").replace(d,"")},Kb:function(a,d){for(var c=[],e=(a||"").split(d),g=0,f=e.length;g<f;g++){var h=b.a.D(e[g]);""!==h&&c.push(h)}return c},Hb:function(a,b){a=a||"";return b.length>a.length?o:a.substring(0,b.length)===b},eb:function(a,b){for(var d="return ("+a+")",c=0;c<b;c++)d="with(sc["+c+"]) { "+d+" } ";return new Function("sc",
d)},kb:function(a,b){if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a!=n;){if(a==b)return l;a=a.parentNode}return o},X:function(a){return b.a.kb(a,a.ownerDocument)},u:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},o:function(b,d,c){var e=m&&k[d];if(!e&&"undefined"!=typeof E){if(a(b,d))var g=c,c=function(a,b){var d=this.checked;b&&(this.checked=b.fb!==l);g.call(this,a);this.checked=d};E(b).bind(d,c)}else!e&&"function"==typeof b.addEventListener?b.addEventListener(d,
c,o):"undefined"!=typeof b.attachEvent?b.attachEvent("on"+d,function(a){c.call(b,a)}):i(Error("Browser doesn't support addEventListener or attachEvent"))},wa:function(b,d){(!b||!b.nodeType)&&i(Error("element must be a DOM node when calling triggerEvent"));if("undefined"!=typeof E){var c=[];a(b,d)&&c.push({fb:b.checked});E(b).trigger(d,c)}else"function"==typeof x.createEvent?"function"==typeof b.dispatchEvent?(c=x.createEvent(e[d]||"HTMLEvents"),c.initEvent(d,l,l,v,0,0,0,0,0,o,o,o,o,0,b),b.dispatchEvent(c)):
i(Error("The supplied element doesn't support dispatchEvent")):"undefined"!=typeof b.fireEvent?(a(b,d)&&(b.checked=b.checked!==l),b.fireEvent("on"+d)):i(Error("Browser doesn't support triggering events"))},d:function(a){return b.la(a)?a():a},ba:function(a,d,c){if(d){var e=/[\w-]+/g,g=a.className.match(e)||[];b.a.n(d.match(e),function(a){var d=b.a.j(g,a);0<=d?c||g.splice(d,1):c&&g.push(a)});a.className=g.join(" ")}},Ra:function(a,d){var c=b.a.d(d);if(c===n||c===F)c="";var e=b.e.firstChild(a);!e||3!=
e.nodeType||b.e.nextSibling(e)?b.e.T(a,[x.createTextNode(c)]):e.data=c;b.a.nb(a)},Pa:function(a,b){a.name=b;if(7>=m)try{a.mergeAttributes(x.createElement("<input name='"+a.name+"'/>"),o)}catch(d){}},nb:function(a){9<=m&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},lb:function(a){if(9<=m){var b=a.style.width;a.style.width=0;a.style.width=b}},Eb:function(a,d){for(var a=b.a.d(a),d=b.a.d(d),c=[],e=a;e<=d;e++)c.push(e);return c},M:function(a){for(var b=[],d=0,c=a.length;d<c;d++)b.push(a[d]);
return b},Ib:6===m,Jb:7===m,Y:m,Ea:function(a,d){for(var c=b.a.M(a.getElementsByTagName("input")).concat(b.a.M(a.getElementsByTagName("textarea"))),e="string"==typeof d?function(a){return a.name===d}:function(a){return d.test(a.name)},g=[],f=c.length-1;0<=f;f--)e(c[f])&&g.push(c[f]);return g},Bb:function(a){return"string"==typeof a&&(a=b.a.D(a))?v.JSON&&v.JSON.parse?v.JSON.parse(a):(new Function("return "+a))():n},sa:function(a,d,c){("undefined"==typeof JSON||"undefined"==typeof JSON.stringify)&&
i(Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js"));return JSON.stringify(b.a.d(a),d,c)},Cb:function(a,d,c){var c=c||{},e=c.params||{},g=c.includeFields||this.Da,f=a;if("object"==typeof a&&"form"===b.a.u(a))for(var f=a.action,h=g.length-1;0<=h;h--)for(var j=b.a.Ea(a,g[h]),k=j.length-1;0<=k;k--)e[j[k].name]=j[k].value;var d=b.a.d(d),m=x.createElement("form");
m.style.display="none";m.action=f;m.method="post";for(var A in d)a=x.createElement("input"),a.name=A,a.value=b.a.sa(b.a.d(d[A])),m.appendChild(a);for(A in e)a=x.createElement("input"),a.name=A,a.value=e[A],m.appendChild(a);x.body.appendChild(m);c.submitter?c.submitter(m):m.submit();setTimeout(function(){m.parentNode.removeChild(m)},0)}}};b.b("utils",b.a);b.b("utils.arrayForEach",b.a.n);b.b("utils.arrayFirst",b.a.ab);b.b("utils.arrayFilter",b.a.da);b.b("utils.arrayGetDistinctValues",b.a.Aa);b.b("utils.arrayIndexOf",
b.a.j);b.b("utils.arrayMap",b.a.W);b.b("utils.arrayPushAll",b.a.O);b.b("utils.arrayRemoveItem",b.a.ea);b.b("utils.extend",b.a.extend);b.b("utils.fieldsIncludedWithJsonPost",b.a.Da);b.b("utils.getFormFields",b.a.Ea);b.b("utils.postJson",b.a.Cb);b.b("utils.parseJson",b.a.Bb);b.b("utils.registerEventHandler",b.a.o);b.b("utils.stringifyJson",b.a.sa);b.b("utils.range",b.a.Eb);b.b("utils.toggleDomNodeCssClass",b.a.ba);b.b("utils.triggerEvent",b.a.wa);b.b("utils.unwrapObservable",b.a.d);Function.prototype.bind||
(Function.prototype.bind=function(a){var b=this,c=Array.prototype.slice.call(arguments),a=c.shift();return function(){return b.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});b.a.f=new function(){var a=0,d="__ko__"+(new Date).getTime(),c={};return{get:function(a,d){var c=b.a.f.getAll(a,o);return c===F?F:c[d]},set:function(a,d,c){c===F&&b.a.f.getAll(a,o)===F||(b.a.f.getAll(a,l)[d]=c)},getAll:function(b,f){var g=b[d];if(!(g&&"null"!==g)){if(!f)return F;g=b[d]="ko"+a++;c[g]={}}return c[g]},
clear:function(a){var b=a[d];b&&(delete c[b],a[d]=n)}}};b.b("utils.domData",b.a.f);b.b("utils.domData.clear",b.a.f.clear);b.a.H=new function(){function a(a,d){var e=b.a.f.get(a,c);e===F&&d&&(e=[],b.a.f.set(a,c,e));return e}function d(c){var e=a(c,o);if(e)for(var e=e.slice(0),j=0;j<e.length;j++)e[j](c);b.a.f.clear(c);"function"==typeof E&&"function"==typeof E.cleanData&&E.cleanData([c]);if(f[c.nodeType])for(e=c.firstChild;c=e;)e=c.nextSibling,8===c.nodeType&&d(c)}var c="__ko_domNodeDisposal__"+(new Date).getTime(),
e={1:l,8:l,9:l},f={1:l,9:l};return{xa:function(b,d){"function"!=typeof d&&i(Error("Callback must be a function"));a(b,l).push(d)},Ma:function(d,e){var f=a(d,o);f&&(b.a.ea(f,e),0==f.length&&b.a.f.set(d,c,F))},G:function(a){if(e[a.nodeType]&&(d(a),f[a.nodeType])){var c=[];b.a.O(c,a.getElementsByTagName("*"));for(var a=0,j=c.length;a<j;a++)d(c[a])}},removeNode:function(a){b.G(a);a.parentNode&&a.parentNode.removeChild(a)}}};b.G=b.a.H.G;b.removeNode=b.a.H.removeNode;b.b("cleanNode",b.G);b.b("removeNode",
b.removeNode);b.b("utils.domNodeDisposal",b.a.H);b.b("utils.domNodeDisposal.addDisposeCallback",b.a.H.xa);b.b("utils.domNodeDisposal.removeDisposeCallback",b.a.H.Ma);b.a.pa=function(a){var d;if("undefined"!=typeof E){if((d=E.clean([a]))&&d[0]){for(a=d[0];a.parentNode&&11!==a.parentNode.nodeType;)a=a.parentNode;a.parentNode&&a.parentNode.removeChild(a)}}else{var c=b.a.D(a).toLowerCase();d=x.createElement("div");c=c.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!c.indexOf("<tr")&&[2,"<table><tbody>",
"</tbody></table>"]||(!c.indexOf("<td")||!c.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];a="ignored<div>"+c[1]+a+c[2]+"</div>";for("function"==typeof v.innerShiv?d.appendChild(v.innerShiv(a)):d.innerHTML=a;c[0]--;)d=d.lastChild;d=b.a.M(d.lastChild.childNodes)}return d};b.a.aa=function(a,d){b.a.ia(a);d=b.a.d(d);if(d!==n&&d!==F)if("string"!=typeof d&&(d=d.toString()),"undefined"!=typeof E)E(a).html(d);else for(var c=b.a.pa(d),e=0;e<c.length;e++)a.appendChild(c[e])};b.b("utils.parseHtmlFragment",
b.a.pa);b.b("utils.setHtml",b.a.aa);var K={};b.t={na:function(a){"function"!=typeof a&&i(Error("You can only pass a function to ko.memoization.memoize()"));var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);K[b]=a;return"<\!--[ko_memo:"+b+"]--\>"},Va:function(a,b){var c=K[a];c===F&&i(Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized."));try{return c.apply(n,b||[]),l}finally{delete K[a]}},Wa:function(a,
d){var c=[];W(a,c);for(var e=0,f=c.length;e<f;e++){var g=c[e].jb,h=[g];d&&b.a.O(h,d);b.t.Va(c[e].yb,h);g.nodeValue="";g.parentNode&&g.parentNode.removeChild(g)}},Ja:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:n}};b.b("memoization",b.t);b.b("memoization.memoize",b.t.na);b.b("memoization.unmemoize",b.t.Va);b.b("memoization.parseMemoText",b.t.Ja);b.b("memoization.unmemoizeDomNodeAndDescendants",b.t.Wa);b.Ca={throttle:function(a,d){a.throttleEvaluation=d;var c=n;return b.h({read:a,write:function(b){clearTimeout(c);
c=setTimeout(function(){a(b)},d)}})},notify:function(a,d){a.equalityComparer="always"==d?q(o):b.m.fn.equalityComparer;return a}};b.b("extenders",b.Ca);b.Ta=function(a,d,c){this.target=a;this.fa=d;this.ib=c;b.s(this,"dispose",this.B)};b.Ta.prototype.B=function(){this.ub=l;this.ib()};b.U=function(){this.w={};b.a.extend(this,b.U.fn);b.s(this,"subscribe",this.ta);b.s(this,"extend",this.extend);b.s(this,"getSubscriptionsCount",this.pb)};b.U.fn={ta:function(a,d,c){var c=c||"change",a=d?a.bind(d):a,e=new b.Ta(this,
a,function(){b.a.ea(this.w[c],e)}.bind(this));this.w[c]||(this.w[c]=[]);this.w[c].push(e);return e},notifySubscribers:function(a,d){d=d||"change";this.w[d]&&b.Q.rb(function(){b.a.n(this.w[d].slice(0),function(b){b&&b.ub!==l&&b.fa(a)})},this)},pb:function(){var a=0,b;for(b in this.w)this.w.hasOwnProperty(b)&&(a+=this.w[b].length);return a},extend:function(a){var d=this;if(a)for(var c in a){var e=b.Ca[c];"function"==typeof e&&(d=e(d,a[c]))}return d}};b.Ga=function(a){return"function"==typeof a.ta&&
"function"==typeof a.notifySubscribers};b.b("subscribable",b.U);b.b("isSubscribable",b.Ga);var y=[];b.Q={bb:function(a){y.push({fa:a,Ba:[]})},end:function(){y.pop()},La:function(a){b.Ga(a)||i(Error("Only subscribable things can act as dependencies"));if(0<y.length){var d=y[y.length-1];d&&!(0<=b.a.j(d.Ba,a))&&(d.Ba.push(a),d.fa(a))}},rb:function(a,b){try{y.push(n),a.call(b)}finally{y.pop()}}};var ea={undefined:l,"boolean":l,number:l,string:l};b.m=function(a){function d(){if(0<arguments.length){if(!d.equalityComparer||
!d.equalityComparer(c,arguments[0]))d.J(),c=arguments[0],d.I();return this}b.Q.La(d);return c}var c=a;b.U.call(d);d.C=function(){return c};d.I=function(){d.notifySubscribers(c)};d.J=function(){d.notifySubscribers(c,"beforeChange")};b.a.extend(d,b.m.fn);b.s(d,"peek",d.C);b.s(d,"valueHasMutated",d.I);b.s(d,"valueWillMutate",d.J);return d};b.m.fn={equalityComparer:function(a,b){return a===n||typeof a in ea?a===b:o}};var z=b.m.Db="__ko_proto__";b.m.fn[z]=b.m;b.ka=function(a,d){return a===n||a===F||a[z]===
F?o:a[z]===d?l:b.ka(a[z],d)};b.la=function(a){return b.ka(a,b.m)};b.Ha=function(a){return"function"==typeof a&&a[z]===b.m||"function"==typeof a&&a[z]===b.h&&a.qb?l:o};b.b("observable",b.m);b.b("isObservable",b.la);b.b("isWriteableObservable",b.Ha);b.S=function(a){0==arguments.length&&(a=[]);a!==n&&(a!==F&&!("length"in a))&&i(Error("The argument passed when initializing an observable array must be an array, or null, or undefined."));var d=b.m(a);b.a.extend(d,b.S.fn);return d};b.S.fn={remove:function(a){for(var b=
this.C(),c=[],e="function"==typeof a?a:function(b){return b===a},f=0;f<b.length;f++){var g=b[f];e(g)&&(0===c.length&&this.J(),c.push(g),b.splice(f,1),f--)}c.length&&this.I();return c},removeAll:function(a){if(a===F){var d=this.C(),c=d.slice(0);this.J();d.splice(0,d.length);this.I();return c}return!a?[]:this.remove(function(d){return 0<=b.a.j(a,d)})},destroy:function(a){var b=this.C(),c="function"==typeof a?a:function(b){return b===a};this.J();for(var e=b.length-1;0<=e;e--)c(b[e])&&(b[e]._destroy=
l);this.I()},destroyAll:function(a){return a===F?this.destroy(q(l)):!a?[]:this.destroy(function(d){return 0<=b.a.j(a,d)})},indexOf:function(a){var d=this();return b.a.j(d,a)},replace:function(a,b){var c=this.indexOf(a);0<=c&&(this.J(),this.C()[c]=b,this.I())}};b.a.n("pop push reverse shift sort splice unshift".split(" "),function(a){b.S.fn[a]=function(){var b=this.C();this.J();b=b[a].apply(b,arguments);this.I();return b}});b.a.n(["slice"],function(a){b.S.fn[a]=function(){var b=this();return b[a].apply(b,
arguments)}});b.b("observableArray",b.S);b.h=function(a,d,c){function e(){b.a.n(t,function(a){a.B()});t=[]}function f(){var a=h.throttleEvaluation;a&&0<=a?(clearTimeout(y),y=setTimeout(g,a)):g()}function g(){if(!m)if(k&&J())r();else{m=l;try{var a=b.a.W(t,function(a){return a.target});b.Q.bb(function(d){var c;0<=(c=b.a.j(a,d))?a[c]=F:t.push(d.ta(f))});for(var c=p.call(d),e=a.length-1;0<=e;e--)a[e]&&t.splice(e,1)[0].B();k=l;h.notifySubscribers(j,"beforeChange");j=c}finally{b.Q.end()}h.notifySubscribers(j);
m=o}}function h(){if(0<arguments.length)return"function"===typeof s?s.apply(d,arguments):i(Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.")),this;k||g();b.Q.La(h);return j}var j,k=o,m=o,p=a;p&&"object"==typeof p?(c=p,p=c.read):(c=c||{},p||(p=c.read));"function"!=typeof p&&i(Error("Pass a function that returns the value of the ko.computed"));var s=c.write;d||(d=c.owner);var t=[],r=e,w="object"==typeof c.disposeWhenNodeIsRemoved?
c.disposeWhenNodeIsRemoved:n,J=c.disposeWhen||q(o);if(w){r=function(){b.a.H.Ma(w,arguments.callee);e()};b.a.H.xa(w,r);var u=J,J=function(){return!b.a.X(w)||u()}}var y=n;h.C=function(){k||g();return j};h.ob=function(){return t.length};h.qb="function"===typeof c.write;h.B=function(){r()};b.U.call(h);b.a.extend(h,b.h.fn);c.deferEvaluation!==l&&g();b.s(h,"peek",h.C);b.s(h,"dispose",h.B);b.s(h,"getDependenciesCount",h.ob);return h};b.tb=function(a){return b.ka(a,b.h)};w=b.m.Db;b.h[w]=b.m;b.h.fn={};b.h.fn[w]=
b.h;b.b("dependentObservable",b.h);b.b("computed",b.h);b.b("isComputed",b.tb);b.Ua=function(a){0==arguments.length&&i(Error("When calling ko.toJS, pass the object you want to convert."));return V(a,function(a){for(var c=0;b.la(a)&&10>c;c++)a=a();return a})};b.toJSON=function(a,d,c){a=b.Ua(a);return b.a.sa(a,d,c)};b.b("toJS",b.Ua);b.b("toJSON",b.toJSON);b.k={r:function(a){switch(b.a.u(a)){case "option":return a.__ko__hasDomDataOptionValue__===l?b.a.f.get(a,b.c.options.oa):7>=b.a.Y?a.getAttributeNode("value").specified?
a.value:a.text:a.value;case "select":return 0<=a.selectedIndex?b.k.r(a.options[a.selectedIndex]):F;default:return a.value}},V:function(a,d){switch(b.a.u(a)){case "option":switch(typeof d){case "string":b.a.f.set(a,b.c.options.oa,F);"__ko__hasDomDataOptionValue__"in a&&delete a.__ko__hasDomDataOptionValue__;a.value=d;break;default:b.a.f.set(a,b.c.options.oa,d),a.__ko__hasDomDataOptionValue__=l,a.value="number"===typeof d?d:""}break;case "select":for(var c=a.options.length-1;0<=c;c--)if(b.k.r(a.options[c])==
d){a.selectedIndex=c;break}break;default:if(d===n||d===F)d="";a.value=d}}};b.b("selectExtensions",b.k);b.b("selectExtensions.readValue",b.k.r);b.b("selectExtensions.writeValue",b.k.V);var ca=/\@ko_token_(\d+)\@/g,fa=/^[\_$a-z][\_$a-z0-9]*(\[.*?\])*(\.[\_$a-z][\_$a-z0-9]*(\[.*?\])*)*$/i,ga=["true","false"];b.g={F:[],Z:function(a){var d=b.a.D(a);if(3>d.length)return[];"{"===d.charAt(0)&&(d=d.substring(1,d.length-1));for(var a=[],c=n,e,f=0;f<d.length;f++){var g=d.charAt(f);if(c===n)switch(g){case '"':case "'":case "/":c=
f,e=g}else if(g==e&&"\\"!==d.charAt(f-1)){g=d.substring(c,f+1);a.push(g);var h="@ko_token_"+(a.length-1)+"@",d=d.substring(0,c)+h+d.substring(f+1),f=f-(g.length-h.length),c=n}}e=c=n;for(var j=0,k=n,f=0;f<d.length;f++){g=d.charAt(f);if(c===n)switch(g){case "{":c=f;k=g;e="}";break;case "(":c=f;k=g;e=")";break;case "[":c=f,k=g,e="]"}g===k?j++:g===e&&(j--,0===j&&(g=d.substring(c,f+1),a.push(g),h="@ko_token_"+(a.length-1)+"@",d=d.substring(0,c)+h+d.substring(f+1),f-=g.length-h.length,c=n))}e=[];d=d.split(",");
c=0;for(f=d.length;c<f;c++)j=d[c],k=j.indexOf(":"),0<k&&k<j.length-1?(g=j.substring(k+1),e.push({key:I(j.substring(0,k),a),value:I(g,a)})):e.push({unknown:I(j,a)});return e},$:function(a){for(var d="string"===typeof a?b.g.Z(a):a,c=[],a=[],e,f=0;e=d[f];f++)if(0<c.length&&c.push(","),e.key){var g;a:{g=e.key;var h=b.a.D(g);switch(h.length&&h.charAt(0)){case "'":case '"':break a;default:g="'"+h+"'"}}e=e.value;c.push(g);c.push(":");c.push(e);h=b.a.D(e);if(0<=b.a.j(ga,b.a.D(h).toLowerCase())?0:h.match(fa)!==
n)0<a.length&&a.push(", "),a.push(g+" : function(__ko_value) { "+e+" = __ko_value; }")}else e.unknown&&c.push(e.unknown);d=c.join("");0<a.length&&(d=d+", '_ko_property_writers' : { "+a.join("")+" } ");return d},wb:function(a,d){for(var c=0;c<a.length;c++)if(b.a.D(a[c].key)==d)return l;return o},ca:function(a,d,c,e,f){if(!a||!b.Ha(a)){if((a=d()._ko_property_writers)&&a[c])a[c](e)}else(!f||a()!==e)&&a(e)}};b.b("expressionRewriting",b.g);b.b("expressionRewriting.bindingRewriteValidators",b.g.F);b.b("expressionRewriting.parseObjectLiteral",
b.g.Z);b.b("expressionRewriting.preProcessBindings",b.g.$);b.b("jsonExpressionRewriting",b.g);b.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",b.g.$);var D="<\!--test--\>"===x.createComment("test").text,ba=D?/^<\!--\s*ko\s+(.*\:.*)\s*--\>$/:/^\s*ko\s+(.*\:.*)\s*$/,aa=D?/^<\!--\s*\/ko\s*--\>$/:/^\s*\/ko\s*$/,ha={ul:l,ol:l};b.e={z:{},childNodes:function(a){return u(a)?U(a):a.childNodes},ja:function(a){if(u(a))for(var a=b.e.childNodes(a),d=0,c=a.length;d<c;d++)b.removeNode(a[d]);else b.a.ia(a)},
T:function(a,d){if(u(a)){b.e.ja(a);for(var c=a.nextSibling,e=0,f=d.length;e<f;e++)c.parentNode.insertBefore(d[e],c)}else b.a.T(a,d)},Ka:function(a,b){u(a)?a.parentNode.insertBefore(b,a.nextSibling):a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Fa:function(a,b,c){u(a)?a.parentNode.insertBefore(b,c.nextSibling):c.nextSibling?a.insertBefore(b,c.nextSibling):a.appendChild(b)},firstChild:function(a){return!u(a)?a.firstChild:!a.nextSibling||C(a.nextSibling)?n:a.nextSibling},nextSibling:function(a){u(a)&&
(a=T(a));return a.nextSibling&&C(a.nextSibling)?n:a.nextSibling},Xa:function(a){return(a=u(a))?a[1]:n},Ia:function(a){if(ha[b.a.u(a)]){var d=a.firstChild;if(d){do if(1===d.nodeType){var c;c=d.firstChild;var e=n;if(c){do if(e)e.push(c);else if(u(c)){var f=T(c,l);f?c=f:e=[c]}else C(c)&&(e=[c]);while(c=c.nextSibling)}if(c=e){e=d.nextSibling;for(f=0;f<c.length;f++)e?a.insertBefore(c[f],e):a.appendChild(c[f])}}while(d=d.nextSibling)}}}};b.b("virtualElements",b.e);b.b("virtualElements.allowedBindings",
b.e.z);b.b("virtualElements.emptyNode",b.e.ja);b.b("virtualElements.insertAfter",b.e.Fa);b.b("virtualElements.prepend",b.e.Ka);b.b("virtualElements.setDomNodeChildren",b.e.T);b.K=function(){this.cb={}};b.a.extend(b.K.prototype,{nodeHasBindings:function(a){switch(a.nodeType){case 1:return a.getAttribute("data-bind")!=n;case 8:return b.e.Xa(a)!=n;default:return o}},getBindings:function(a,b){var c=this.getBindingsString(a,b);return c?this.parseBindingsString(c,b):n},getBindingsString:function(a){switch(a.nodeType){case 1:return a.getAttribute("data-bind");
case 8:return b.e.Xa(a);default:return n}},parseBindingsString:function(a,d){try{var c=d.$data,c="object"==typeof c&&c!=n?[c,d]:[d],e=c.length,f=this.cb,g=e+"_"+a,h;if(!(h=f[g])){var j=" { "+b.g.$(a)+" } ";h=f[g]=b.a.eb(j,e)}return h(c)}catch(k){i(Error("Unable to parse bindings.\nMessage: "+k+";\nBindings value: "+a))}}});b.K.instance=new b.K;b.b("bindingProvider",b.K);b.c={};b.A=function(a,d){d?(b.a.extend(this,d),this.$parentContext=d,this.$parent=d.$data,this.$parents=(d.$parents||[]).slice(0),
this.$parents.unshift(this.$parent)):(this.$parents=[],this.$root=a,this.ko=b);this.$data=a};b.A.prototype.createChildContext=function(a){return new b.A(a,this)};b.A.prototype.extend=function(a){var d=b.a.extend(new b.A,this);return b.a.extend(d,a)};b.Sa=function(a,d){if(2==arguments.length)b.a.f.set(a,"__ko_bindingContext__",d);else return b.a.f.get(a,"__ko_bindingContext__")};b.za=function(a,d,c){1===a.nodeType&&b.e.Ia(a);return Q(a,d,c,l)};b.Ya=function(a,b){(1===b.nodeType||8===b.nodeType)&&S(a,
b,l)};b.ya=function(a,b){b&&(1!==b.nodeType&&8!==b.nodeType)&&i(Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node"));b=b||v.document.body;R(a,b,l)};b.ha=function(a){switch(a.nodeType){case 1:case 8:var d=b.Sa(a);if(d)return d;if(a.parentNode)return b.ha(a.parentNode)}return F};b.hb=function(a){return(a=b.ha(a))?a.$data:F};b.b("bindingHandlers",b.c);b.b("applyBindings",b.ya);b.b("applyBindingsToDescendants",b.Ya);b.b("applyBindingsToNode",b.za);
b.b("contextFor",b.ha);b.b("dataFor",b.hb);b.a.n(["click"],function(a){b.c[a]={init:function(d,c,e,f){return b.c.event.init.call(this,d,function(){var b={};b[a]=c();return b},e,f)}}});b.c.event={init:function(a,d,c,e){var f=d()||{},g;for(g in f)(function(){var f=g;"string"==typeof f&&b.a.o(a,f,function(a){var g,m=d()[f];if(m){var p=c();try{var s=b.a.M(arguments);s.unshift(e);g=m.apply(e,s)}finally{g!==l&&(a.preventDefault?a.preventDefault():a.returnValue=o)}p[f+"Bubble"]===o&&(a.cancelBubble=l,a.stopPropagation&&
a.stopPropagation())}})})()}};b.c.submit={init:function(a,d,c,e){"function"!=typeof d()&&i(Error("The value for a submit binding must be a function"));b.a.o(a,"submit",function(b){var c,h=d();try{c=h.call(e,a)}finally{c!==l&&(b.preventDefault?b.preventDefault():b.returnValue=o)}})}};b.c.visible={update:function(a,d){var c=b.a.d(d()),e="none"!=a.style.display;c&&!e?a.style.display="":!c&&e&&(a.style.display="none")}};b.c.enable={update:function(a,d){var c=b.a.d(d());c&&a.disabled?a.removeAttribute("disabled"):
!c&&!a.disabled&&(a.disabled=l)}};b.c.disable={update:function(a,d){b.c.enable.update(a,function(){return!b.a.d(d())})}};b.c.value={init:function(a,d,c){function e(){var e=d(),f=b.k.r(a);b.g.ca(e,c,"value",f,l)}var f=["change"],g=c().valueUpdate;g&&("string"==typeof g&&(g=[g]),b.a.O(f,g),f=b.a.Aa(f));if(b.a.Y&&("input"==a.tagName.toLowerCase()&&"text"==a.type&&"off"!=a.autocomplete&&(!a.form||"off"!=a.form.autocomplete))&&-1==b.a.j(f,"propertychange")){var h=o;b.a.o(a,"propertychange",function(){h=
l});b.a.o(a,"blur",function(){if(h){h=o;e()}})}b.a.n(f,function(c){var d=e;if(b.a.Hb(c,"after")){d=function(){setTimeout(e,0)};c=c.substring(5)}b.a.o(a,c,d)})},update:function(a,d){var c="select"===b.a.u(a),e=b.a.d(d()),f=b.k.r(a),g=e!=f;0===e&&(0!==f&&"0"!==f)&&(g=l);g&&(f=function(){b.k.V(a,e)},f(),c&&setTimeout(f,0));c&&0<a.length&&X(a,e,o)}};b.c.options={update:function(a,d,c){"select"!==b.a.u(a)&&i(Error("options binding applies only to SELECT elements"));for(var e=0==a.length,f=b.a.W(b.a.da(a.childNodes,
function(a){return a.tagName&&"option"===b.a.u(a)&&a.selected}),function(a){return b.k.r(a)||a.innerText||a.textContent}),g=a.scrollTop,h=b.a.d(d());0<a.length;)b.G(a.options[0]),a.remove(0);if(h){var c=c(),j=c.optionsIncludeDestroyed;"number"!=typeof h.length&&(h=[h]);if(c.optionsCaption){var k=x.createElement("option");b.a.aa(k,c.optionsCaption);b.k.V(k,F);a.appendChild(k)}for(var d=0,m=h.length;d<m;d++){var p=h[d];if(!p||!p._destroy||j){var k=x.createElement("option"),s=function(a,b,c){var d=typeof b;
return"function"==d?b(a):"string"==d?a[b]:c},t=s(p,c.optionsValue,p);b.k.V(k,b.a.d(t));p=s(p,c.optionsText,t);b.a.Ra(k,p);a.appendChild(k)}}h=a.getElementsByTagName("option");d=j=0;for(m=h.length;d<m;d++)0<=b.a.j(f,b.k.r(h[d]))&&(b.a.Qa(h[d],l),j++);a.scrollTop=g;e&&"value"in c&&X(a,b.a.d(c.value),l);b.a.lb(a)}}};b.c.options.oa="__ko.optionValueDomData__";b.c.selectedOptions={init:function(a,d,c){b.a.o(a,"change",function(){var e=d(),f=[];b.a.n(a.getElementsByTagName("option"),function(a){a.selected&&
f.push(b.k.r(a))});b.g.ca(e,c,"value",f)})},update:function(a,d){"select"!=b.a.u(a)&&i(Error("values binding applies only to SELECT elements"));var c=b.a.d(d());c&&"number"==typeof c.length&&b.a.n(a.getElementsByTagName("option"),function(a){var d=0<=b.a.j(c,b.k.r(a));b.a.Qa(a,d)})}};b.c.text={update:function(a,d){b.a.Ra(a,d())}};b.e.z.text=l;b.c.html={init:function(){return{controlsDescendantBindings:l}},update:function(a,d){b.a.aa(a,d())}};b.c.css={update:function(a,d){var c=b.a.d(d());if("object"==
typeof c)for(var e in c){var f=b.a.d(c[e]);b.a.ba(a,e,f)}else c=String(c||""),b.a.ba(a,a.__ko__cssValue,o),a.__ko__cssValue=c,b.a.ba(a,c,l)}};b.c.style={update:function(a,d){var c=b.a.d(d()||{}),e;for(e in c)if("string"==typeof e){var f=b.a.d(c[e]);a.style[e]=f||""}}};b.c.uniqueName={init:function(a,d){if(d()){var c="ko_unique_"+ ++b.c.uniqueName.gb;b.a.Pa(a,c)}}};b.c.uniqueName.gb=0;b.c.checked={init:function(a,d,c){b.a.o(a,"click",function(){var e;if("checkbox"==a.type)e=a.checked;else if("radio"==
a.type&&a.checked)e=a.value;else return;var f=d();"checkbox"==a.type&&b.a.d(f)instanceof Array?(e=b.a.j(b.a.d(f),a.value),a.checked&&0>e?f.push(a.value):!a.checked&&0<=e&&f.splice(e,1)):b.g.ca(f,c,"checked",e,l)});"radio"==a.type&&!a.name&&b.c.uniqueName.init(a,q(l))},update:function(a,d){var c=b.a.d(d());"checkbox"==a.type?a.checked=c instanceof Array?0<=b.a.j(c,a.value):c:"radio"==a.type&&(a.checked=a.value==c)}};var Y={"class":"className","for":"htmlFor"};b.c.attr={update:function(a,d){var c=b.a.d(d())||
{},e;for(e in c)if("string"==typeof e){var f=b.a.d(c[e]),g=f===o||f===n||f===F;g&&a.removeAttribute(e);8>=b.a.Y&&e in Y?(e=Y[e],g?a.removeAttribute(e):a[e]=f):g||a.setAttribute(e,f.toString());"name"===e&&b.a.Pa(a,g?"":f.toString())}}};b.c.hasfocus={init:function(a,d,c){function e(e){a.__ko_hasfocusUpdating=l;var f=a.ownerDocument;"activeElement"in f&&(e=f.activeElement===a);f=d();b.g.ca(f,c,"hasfocus",e,l);a.__ko_hasfocusUpdating=o}var f=e.bind(n,l),g=e.bind(n,o);b.a.o(a,"focus",f);b.a.o(a,"focusin",
f);b.a.o(a,"blur",g);b.a.o(a,"focusout",g)},update:function(a,d){if(!a.__ko_hasfocusUpdating){var c=b.a.d(d());c?a.focus():a.blur();b.a.wa(a,c?"focusin":"focusout")}}};b.c["with"]={p:function(a){return function(){var d=a();return{"if":d,data:d,templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c["with"].p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c["with"].p(d),c,e,f)}};b.g.F["with"]=o;b.e.z["with"]=l;b.c["if"]={p:function(a){return function(){return{"if":a(),
templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c["if"].p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c["if"].p(d),c,e,f)}};b.g.F["if"]=o;b.e.z["if"]=l;b.c.ifnot={p:function(a){return function(){return{ifnot:a(),templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c.ifnot.p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c.ifnot.p(d),c,e,f)}};b.g.F.ifnot=o;b.e.z.ifnot=l;b.c.foreach={p:function(a){return function(){var d=
b.a.d(a());return!d||"number"==typeof d.length?{foreach:d,templateEngine:b.q.L}:{foreach:d.data,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,templateEngine:b.q.L}}},init:function(a,d){return b.c.template.init(a,b.c.foreach.p(d))},update:function(a,d,c,e,f){return b.c.template.update(a,b.c.foreach.p(d),c,e,f)}};b.g.F.foreach=o;b.e.z.foreach=l;b.v=function(){};b.v.prototype.renderTemplateSource=function(){i(Error("Override renderTemplateSource"))};
b.v.prototype.createJavaScriptEvaluatorBlock=function(){i(Error("Override createJavaScriptEvaluatorBlock"))};b.v.prototype.makeTemplateSource=function(a,d){if("string"==typeof a){var d=d||x,c=d.getElementById(a);c||i(Error("Cannot find template with ID "+a));return new b.l.i(c)}if(1==a.nodeType||8==a.nodeType)return new b.l.N(a);i(Error("Unknown template type: "+a))};b.v.prototype.renderTemplate=function(a,b,c,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,b,c)};b.v.prototype.isTemplateRewritten=
function(a,b){return this.allowTemplateRewriting===o?l:this.makeTemplateSource(a,b).data("isRewritten")};b.v.prototype.rewriteTemplate=function(a,b,c){a=this.makeTemplateSource(a,c);b=b(a.text());a.text(b);a.data("isRewritten",l)};b.b("templateEngine",b.v);var ia=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi,ja=/<\!--\s*ko\b\s*([\s\S]*?)\s*--\>/g;b.ua={mb:function(a,d,c){d.isTemplateRewritten(a,c)||d.rewriteTemplate(a,function(a){return b.ua.zb(a,
d)},c)},zb:function(a,b){return a.replace(ia,function(a,e,f,g,h,j,k){return P(k,e,b)}).replace(ja,function(a,e){return P(e,"<\!-- ko --\>",b)})},Za:function(a){return b.t.na(function(d,c){d.nextSibling&&b.za(d.nextSibling,a,c)})}};b.b("__tr_ambtns",b.ua.Za);b.l={};b.l.i=function(a){this.i=a};b.l.i.prototype.text=function(){var a=b.a.u(this.i),a="script"===a?"text":"textarea"===a?"value":"innerHTML";if(0==arguments.length)return this.i[a];var d=arguments[0];"innerHTML"===a?b.a.aa(this.i,d):this.i[a]=
d};b.l.i.prototype.data=function(a){if(1===arguments.length)return b.a.f.get(this.i,"templateSourceData_"+a);b.a.f.set(this.i,"templateSourceData_"+a,arguments[1])};b.l.N=function(a){this.i=a};b.l.N.prototype=new b.l.i;b.l.N.prototype.text=function(){if(0==arguments.length){var a=b.a.f.get(this.i,"__ko_anon_template__")||{};a.va===F&&a.ga&&(a.va=a.ga.innerHTML);return a.va}b.a.f.set(this.i,"__ko_anon_template__",{va:arguments[0]})};b.l.i.prototype.nodes=function(){if(0==arguments.length)return(b.a.f.get(this.i,
"__ko_anon_template__")||{}).ga;b.a.f.set(this.i,"__ko_anon_template__",{ga:arguments[0]})};b.b("templateSources",b.l);b.b("templateSources.domElement",b.l.i);b.b("templateSources.anonymousTemplate",b.l.N);var H;b.ra=function(a){a!=F&&!(a instanceof b.v)&&i(Error("templateEngine must inherit from ko.templateEngine"));H=a};b.qa=function(a,d,c,e,f){c=c||{};(c.templateEngine||H)==F&&i(Error("Set a template engine before calling renderTemplate"));f=f||"replaceChildren";if(e){var g=G(e);return b.h(function(){var h=
d&&d instanceof b.A?d:new b.A(b.a.d(d)),j="function"==typeof a?a(h.$data,h):a,h=M(e,f,j,h,c);"replaceNode"==f&&(e=h,g=G(e))},n,{disposeWhen:function(){return!g||!b.a.X(g)},disposeWhenNodeIsRemoved:g&&"replaceNode"==f?g.parentNode:g})}return b.t.na(function(e){b.qa(a,d,c,e,"replaceNode")})};b.Fb=function(a,d,c,e,f){function g(a,b){N(b,j);c.afterRender&&c.afterRender(b,a)}function h(d,e){j=f.createChildContext(b.a.d(d));j.$index=e;var g="function"==typeof a?a(d,j):a;return M(n,"ignoreTargetNode",g,
j,c)}var j;return b.h(function(){var a=b.a.d(d)||[];"undefined"==typeof a.length&&(a=[a]);a=b.a.da(a,function(a){return c.includeDestroyed||a===F||a===n||!b.a.d(a._destroy)});b.a.Oa(e,a,h,c,g)},n,{disposeWhenNodeIsRemoved:e})};b.c.template={init:function(a,d){var c=b.a.d(d());if("string"!=typeof c&&!c.name&&(1==a.nodeType||8==a.nodeType))c=1==a.nodeType?a.childNodes:b.e.childNodes(a),c=b.a.Ab(c),(new b.l.N(a)).nodes(c);return{controlsDescendantBindings:l}},update:function(a,d,c,e,f){d=b.a.d(d());
e=l;"string"==typeof d?c=d:(c=d.name,"if"in d&&(e=e&&b.a.d(d["if"])),"ifnot"in d&&(e=e&&!b.a.d(d.ifnot)));var g=n;"object"===typeof d&&"foreach"in d?g=b.Fb(c||a,e&&d.foreach||[],d,a,f):e?(f="object"==typeof d&&"data"in d?f.createChildContext(b.a.d(d.data)):f,g=b.qa(c||a,f,d,a)):b.e.ja(a);f=g;(d=b.a.f.get(a,"__ko__templateSubscriptionDomDataKey__"))&&"function"==typeof d.B&&d.B();b.a.f.set(a,"__ko__templateSubscriptionDomDataKey__",f)}};b.g.F.template=function(a){a=b.g.Z(a);return 1==a.length&&a[0].unknown||
b.g.wb(a,"name")?n:"This template engine does not support anonymous templates nested within its templates"};b.e.z.template=l;b.b("setTemplateEngine",b.ra);b.b("renderTemplate",b.qa);b.a.P=function(a,d,c){if(c===F)return b.a.P(a,d,1)||b.a.P(a,d,10)||b.a.P(a,d,Number.MAX_VALUE);for(var a=a||[],d=d||[],e=a,f=d,g=[],h=0;h<=f.length;h++)g[h]=[];for(var h=0,j=Math.min(e.length,c);h<=j;h++)g[0][h]=h;h=1;for(j=Math.min(f.length,c);h<=j;h++)g[h][0]=h;for(var j=e.length,k,m=f.length,h=1;h<=j;h++){k=Math.max(1,
h-c);for(var p=Math.min(m,h+c);k<=p;k++)g[k][h]=e[h-1]===f[k-1]?g[k-1][h-1]:Math.min(g[k-1][h]===F?Number.MAX_VALUE:g[k-1][h]+1,g[k][h-1]===F?Number.MAX_VALUE:g[k][h-1]+1)}c=a.length;e=d.length;f=[];h=g[e][c];if(h===F)g=n;else{for(;0<c||0<e;){j=g[e][c];m=0<e?g[e-1][c]:h+1;p=0<c?g[e][c-1]:h+1;k=0<e&&0<c?g[e-1][c-1]:h+1;if(m===F||m<j-1)m=h+1;if(p===F||p<j-1)p=h+1;k<j-1&&(k=h+1);m<=p&&m<k?(f.push({status:"added",value:d[e-1]}),e--):(p<m&&p<k?f.push({status:"deleted",value:a[c-1]}):(f.push({status:"retained",
value:a[c-1]}),e--),c--)}g=f.reverse()}return g};b.b("utils.compareArrays",b.a.P);b.a.Oa=function(a,d,c,e,f){for(var d=d||[],e=e||{},g=b.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")===F,h=b.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")||[],j=b.a.W(h,function(a){return a.$a}),k=b.a.P(j,d),d=[],m=0,p=[],s=0,j=[],t=n,r=0,w=k.length;r<w;r++)switch(k[r].status){case "retained":var u=h[m];u.sb(s);s=d.push(u);0<u.R.length&&(t=u.R[u.R.length-1]);m++;break;case "deleted":h[m].h.B();
L(h[m].R);b.a.n(h[m].R,function(a){p.push({element:a,index:r,value:k[r].value});t=a});m++;break;case "added":for(var u=k[r].value,y=b.m(s),s=$(a,c,u,f,y),z=s.xb,s=d.push({$a:k[r].value,R:z,h:s.h,sb:y}),C=0,D=z.length;C<D;C++){var A=z[C];j.push({element:A,index:r,value:k[r].value});t==n?b.e.Ka(a,A):b.e.Fa(a,A,t);t=A}f&&f(u,z,y)}b.a.n(p,function(a){b.G(a.element)});c=o;if(!g){if(e.afterAdd)for(r=0;r<j.length;r++)e.afterAdd(j[r].element,j[r].index,j[r].value);if(e.beforeRemove){for(r=0;r<p.length;r++)e.beforeRemove(p[r].element,
p[r].index,p[r].value);c=l}}if(!c&&p.length)for(r=0;r<p.length;r++)e=p[r].element,e.parentNode&&e.parentNode.removeChild(e);b.a.f.set(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult",d)};b.b("utils.setDomNodeChildrenFromArrayMapping",b.a.Oa);b.q=function(){this.allowTemplateRewriting=o};b.q.prototype=new b.v;b.q.prototype.renderTemplateSource=function(a){var d=!(9>b.a.Y)&&a.nodes?a.nodes():n;if(d)return b.a.M(d.cloneNode(l).childNodes);a=a.text();return b.a.pa(a)};b.q.L=new b.q;b.ra(b.q.L);
b.b("nativeTemplateEngine",b.q);b.ma=function(){var a=this.vb=function(){if("undefined"==typeof E||!E.tmpl)return 0;try{if(0<=E.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,c,e){e=e||{};2>a&&i(Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later."));var f=b.data("precompiled");f||(f=b.text()||"",f=E.template(n,"{{ko_with $item.koBindingContext}}"+f+"{{/ko_with}}"),b.data("precompiled",f));
b=[c.$data];c=E.extend({koBindingContext:c},e.templateOptions);c=E.tmpl(f,b,c);c.appendTo(x.createElement("div"));E.fragments={};return c};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){x.write("<script type='text/html' id='"+a+"'>"+b+"<\/script>")};0<a&&(E.tmpl.tag.ko_code={open:"__.push($1 || '');"},E.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};b.ma.prototype=new b.v;w=new b.ma;0<w.vb&&b.ra(w);b.b("jqueryTmplTemplateEngine",
b.ma)}"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?Z(module.exports||exports):"function"===typeof define&&define.amd?define(["exports"],Z):Z(v.ko={});l;
})();
